pluginManagement {
    repositories {
        maven {
            name = 'GTNH Maven'
            url = 'https://nexus.gtnewhorizons.com/repository/public/'
            mavenContent {
                includeGroup 'com.gtnewhorizons'
                includeGroup 'com.gtnewhorizons.retrofuturagradle'
            }
        }
        maven { url = 'https://maven.wagyourtail.xyz/releases' }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    versionCatalogs {
        libs {
            from(files('../gradle/libs.versions.toml'))
        }
    }
}

rootProject.name = 'skinsrestorer-forge-1.12'
